// SPDX-License-Identifier: GPL-3.0-or-later
#pragma once
static const char PASSWORDS_PAGE[] PROGMEM=R"HTML(<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Samsung · Пароли</title>__STYLE__</head><body>__NAV__<main><h1>Пароли</h1><p>Меняйте только нужные пароли. Пустые поля сохраняют текущие значения. Сохранённые пароли не отображаются.</p><p id="message" class="status" role="status">Проверяем хранилище…</p><form id="form"><h2>Веб-интерфейс</h2><p class="muted">Пользователь admin. Один пароль для настроек и пульта управления.</p><label>Новый пароль<input type="password" name="web_password" minlength="16" maxlength="64" autocomplete="new-password"></label><label>Повторите пароль<input type="password" name="web_confirm" minlength="16" maxlength="64" autocomplete="new-password"></label><h2>Локальное OTA</h2><p class="muted">Для загрузки прошивки с компьютера. Подписанные обновления GitHub используют отдельную проверку подписи.</p><label>Новый пароль OTA<input type="password" name="ota_password" minlength="16" maxlength="64" autocomplete="new-password"></label><label>Повторите пароль OTA<input type="password" name="ota_confirm" minlength="16" maxlength="64" autocomplete="new-password"></label><h2>Точка настройки Wi-Fi</h2><p class="muted">Пароль сети Samsung-Setup. Пароль домашней Wi-Fi-сети и MQTT здесь не меняются.</p><label>Новый пароль точки настройки<input type="password" name="setup_password" minlength="8" maxlength="63" autocomplete="new-password"></label><label>Повторите пароль точки настройки<input type="password" name="setup_confirm" minlength="8" maxlength="63" autocomplete="new-password"></label><p>Веб и OTA: 16–64 символа; точка настройки: 8–63. Латинские буквы, цифры и знаки ASCII без пробелов.</p><p>После изменения плата перезагрузится. При смене веб-пароля браузер может запросить вход заново.</p><button id="save" disabled>Сохранить и перезагрузить</button></form><section class="card"><h2>Если пароль забыт</h2><p>Эта страница предназначена для смены паролей при наличии доступа. Восстановление забытого пароля пока не реализовано. Сохраните новые пароли перед применением.</p></section></main><footer>4vrs · Samsung-ESP32</footer><script>
const token='__TOKEN__',form=document.getElementById('form'),message=document.getElementById('message'),save=document.getElementById('save');
async function init(){try{let r=await fetch('/settings/config',{cache:'no-store',signal:AbortSignal.timeout(5000)});if(!r.ok)throw Error('HTTP '+r.status);let s=await r.json();save.disabled=!s.credentials_ready;message.textContent=s.credentials_ready?'Пароли сохранены на устройстве. Можно изменить выбранные.':'Хранилище паролей недоступно.'}catch(e){message.textContent='Не удалось проверить хранилище: '+e.message}}
form.onsubmit=async e=>{e.preventDefault();const body=new URLSearchParams({token});let changed=false;
 for(const name of ['web','ota','setup']){let value=form.elements[name+'_password'].value,repeat=form.elements[name+'_confirm'].value;if(value!==repeat){message.textContent='Пароли и подтверждение должны совпадать.';return}if(value){const min=name==='setup'?8:16,max=name==='setup'?63:64;if(value.length<min||value.length>max||!/^[\x21-\x7e]+$/.test(value)){message.textContent='Проверьте длину и символы пароля.';return}changed=true}body.set(name+'_password',value);body.set(name+'_confirm',repeat)}
 if(!changed){message.textContent='Новые пароли не введены. Изменений нет.';return}
 if(!confirm('Сохранить новые пароли и перезагрузить контроллер? Убедитесь, что вы сохранили пароли.'))return;
 save.disabled=true;let submitted=false;
 try{let r=await fetch('/settings/config',{method:'POST',body,signal:AbortSignal.timeout(6000)});if(!r.ok)throw Error(await r.text());let s=await r.json();submitted=true;form.reset();if(s.restarting){for(const input of form.querySelectorAll('input'))input.disabled=true;message.textContent='Пароли сохранены. Контроллер перезагружается. Через 15 секунд откройте страницу заново; при запросе входа используйте новый веб-пароль.'}else{message.textContent='Пароли не изменились. Перезагрузка не требуется.';save.disabled=false}}
 catch(e){message.textContent='Не удалось подтвердить сохранение: '+e.message+'. Если связь прервалась, проверьте вход с новым паролем перед повторной попыткой.'}
 finally{if(!submitted)save.disabled=false}
};init();
</script></body></html>)HTML";
