// SPDX-License-Identifier: GPL-3.0-or-later
#pragma once
static const char WIFI_PAGE[] PROGMEM=R"HTML(<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Samsung · Wi-Fi</title>__STYLE__</head><body data-page="wifi">__NAV__<main><h1>Wi-Fi</h1><p>Подключение к сети 2,4 ГГц</p><p id="message" class="status" role="status">Получаем данные…</p><section class="card"><dl id="info"></dl></section><section class="card" style="margin-top:16px"><h2>Смена сети</h2><p>Для настройки другой сети удалите сохранённое подключение и подключитесь к точке настройки контроллера. MQTT, Modbus и пароли доступа сохранятся.</p><p><a href="/wifi/reset">Сбросить только Wi-Fi</a></p><p>При отсутствии связи с сетью точка настройки запускается примерно через 10 секунд. Подключитесь к <strong id="ap">Samsung-Setup</strong> с её паролем и откройте <a href="http://192.168.4.1:8080/">192.168.4.1:8080</a>.</p><p class="muted">Этот адрес доступен после подключения к точке настройки. Пароль точки можно изменить в разделе «Пароли». После сброса старая сеть автоматически не восстанавливается.</p></section></main><footer>4vrs · Samsung-ESP32</footer><script>
const el=id=>document.getElementById(id);async function refresh(){try{if(document.hidden)return;const r=await fetch('/wifi/status',{cache:'no-store',signal:AbortSignal.timeout(4000)});if(!r.ok)throw Error('HTTP '+r.status);const s=await r.json();const rows=[['Подключение',s.connected?'Подключён':'Нет связи'],['Сеть',s.ssid||'—'],['Адрес',s.ip||'—'],['MAC Wi-Fi',s.mac],['Уровень сигнала',s.rssi==null?'—':s.rssi+' dBm'],['Канал',s.channel==null?'—':s.channel],['Точка настройки',s.ap_active?'Включена':'Выключена']];el('info').replaceChildren();for(const[k,v]of rows){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=v;el('info').append(dt,dd)}el('ap').textContent=s.ap_ssid;el('message').textContent='Данные обновлены'}catch(e){el('message').textContent='Не удалось обновить данные: '+e.message}finally{setTimeout(refresh,5000)}}refresh();
</script></body></html>)HTML";
static const char WIFI_RESET_PAGE[] PROGMEM=R"HTML(<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Samsung · Сброс Wi-Fi</title>__STYLE__</head><body data-page="wifi">__NAV__<main><h1>Сброс Wi-Fi</h1><section class="card"><p>Будут удалены только имя и пароль сохранённой Wi-Fi-сети. Контроллер перезагрузится, и связь по текущему адресу будет потеряна.</p><p><strong>Сохранятся:</strong> настройки MQTT и Modbus, пароли веб-пульта, OTA и точки Samsung-Setup.</p><p>После перезапуска подключитесь к Samsung-Setup с текущим паролем точки настройки. Откройте <a href="http://192.168.4.1:8080/">192.168.4.1:8080</a> и укажите новую сеть. Убедитесь заранее, что знаете пароль Samsung-Setup.</p><label><input type="checkbox" id="ack"> Я знаю пароль точки настройки и понимаю, что текущее подключение будет потеряно</label><button id="reset" disabled>Удалить сеть и перезагрузить</button><p id="message" role="status"></p><p><a href="/wifi">Вернуться к Wi-Fi</a></p></section></main><script>
const token='__TOKEN__',button=document.getElementById('reset'),ack=document.getElementById('ack'),message=document.getElementById('message');ack.onchange=()=>button.disabled=!ack.checked;
button.onclick=async()=>{if(!ack.checked||!confirm('Удалить сохранённую сеть и перезагрузить контроллер? Связь по текущему адресу будет потеряна.'))return;button.disabled=true;ack.disabled=true;try{const r=await fetch('/wifi/reset',{method:'POST',body:new URLSearchParams({token,confirm:'RESET_WIFI'}),signal:AbortSignal.timeout(5000)});if(!r.ok)throw Error(await r.text());message.textContent='Сеть удалена. Подключитесь к Samsung-Setup и откройте 192.168.4.1:8080.'}catch(e){message.textContent='Не удалось подтвердить сброс: '+e.message+'. Если связь пропала, проверьте наличие Samsung-Setup перед повторной попыткой.';ack.disabled=false;button.disabled=!ack.checked}};
</script></body></html>)HTML";
