"""Build English HTML/JS from Russian source templates; fail on missing translations."""
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
UI = ROOT / 'components/samsung_portal'

def generate():
    pairs = {}
    for number, line in enumerate((UI / 'i18n/en.tsv').read_text(encoding='utf-8-sig').splitlines(), 1):
        if not line:
            continue
        if '\t' not in line:
            raise ValueError(f'en.tsv:{number}: expected source<TAB>translation')
        source, target = line.split('\t', 1)
        if not source or not target or '\t' in target or source in pairs:
            raise ValueError(f'en.tsv:{number}: empty, duplicate or malformed translation')
        pairs[source] = target
    if not pairs:
        raise ValueError('Translation catalog is empty')
    pattern = re.compile('|'.join(re.escape(s) for s in sorted(pairs, key=len, reverse=True)))
    output = ['// Generated by tools/build_ui_translations.py. Do not edit.', '#pragma once']
    for path in sorted(UI.glob('*Page.h')) + [UI / 'UiShell.h']:
        for name, html in re.findall(r'static const char (\w+)\[\].*?R"HTML\((.*?)\)HTML";', path.read_text(encoding='utf-8'), re.S):
            if name == 'UI_STYLE':
                continue
            translated = pattern.sub(lambda m: pairs[m[0]], html).replace('lang="ru"', 'lang="en"')
            missing = re.findall(r'.{0,35}[А-Яа-яЁё].{0,60}', translated)
            if missing:
                raise ValueError(f'{name}: untranslated text: {missing}')
            output.append(f'static const char {name}_EN[] PROGMEM=R"HTML({translated})HTML";')
    return '\n'.join(output) + '\n'

if __name__ == '__main__':
    result = generate()
    target = UI / 'UiEnglish.h'
    if '--check' in sys.argv:
        if not target.exists() or target.read_text(encoding='utf-8') != result:
            raise SystemExit('Rebuild UiEnglish.h with python tools/build_ui_translations.py')
    else:
        target.write_text(result, encoding='utf-8')
    print('English UI translations: OK')
